export const CAREBASE_PERMISSIONS = [
  "dashboard.read",
  "hospital.manage",
  "departments.read",
  "departments.manage",
  "staff.read",
  "staff.manage",
  "roles.manage",
  "patients.read",
  "patients.manage",
  "clinical.read",
  "clinical.manage",
  "appointments.read",
  "appointments.manage",
  "beds.read",
  "beds.manage",
  "diagnostics.read",
  "diagnostics.manage",
  "attendance.read",
  "attendance.manage",
  "payments.read",
  "payments.manage",
  "notices.read",
  "notices.manage",
  "notifications.read",
  "reports.read",
  "audit.read",
] as const;

export type CarebasePermission = (typeof CAREBASE_PERMISSIONS)[number];

export const DEFAULT_ROLE_PERMISSIONS: Record<string, CarebasePermission[]> = {
  OWNER: [...CAREBASE_PERMISSIONS],
  ADMIN: [...CAREBASE_PERMISSIONS],
  DOCTOR: [
    "dashboard.read",
    "departments.read",
    "staff.read",
    "patients.read",
    "clinical.read",
    "clinical.manage",
    "appointments.read",
    "appointments.manage",
    "beds.read",
    "diagnostics.read",
    "diagnostics.manage",
    "payments.read",
    "notices.read",
    "notifications.read",
    "reports.read",
  ],
  NURSE: [
    "dashboard.read",
    "departments.read",
    "patients.read",
    "patients.manage",
    "clinical.read",
    "appointments.read",
    "appointments.manage",
    "beds.read",
    "beds.manage",
    "diagnostics.read",
    "attendance.read",
    "notices.read",
    "notifications.read",
  ],
  TECHNICIAN: [
    "dashboard.read",
    "departments.read",
    "patients.read",
    "diagnostics.read",
    "diagnostics.manage",
    "appointments.read",
    "attendance.read",
    "notices.read",
    "notifications.read",
  ],
  RECEPTIONIST: [
    "dashboard.read",
    "departments.read",
    "staff.read",
    "patients.read",
    "patients.manage",
    "appointments.read",
    "appointments.manage",
    "beds.read",
    "beds.manage",
    "payments.read",
    "notices.read",
    "notifications.read",
  ],
  ACCOUNTANT: [
    "dashboard.read",
    "patients.read",
    "appointments.read",
    "payments.read",
    "payments.manage",
    "reports.read",
    "notifications.read",
  ],
  STAFF: [
    "dashboard.read",
    "departments.read",
    "staff.read",
    "attendance.read",
    "notices.read",
    "notifications.read",
  ],
};

export const ROLE_LABELS: Record<string, string> = {
  OWNER: "Hospital owner",
  ADMIN: "Administrator",
  DOCTOR: "Doctor",
  NURSE: "Nurse",
  TECHNICIAN: "Technician",
  RECEPTIONIST: "Receptionist",
  ACCOUNTANT: "Finance",
  STAFF: "Staff",
};

export const SYSTEM_ROLES = Object.keys(DEFAULT_ROLE_PERMISSIONS).map((name) => ({
  name,
  description: ROLE_LABELS[name],
  permissions: DEFAULT_ROLE_PERMISSIONS[name],
}));
